#!/usr/bin/env python3
"""Generate a docker-compose.yml with N DataNodes.

    python scripts/gen_compose.py 5 > docker-compose.yml

Every DataNode gets its own named volume, so data survives container restarts and
a node that comes back is recognised (same id, same blocks).
"""
import sys

n = int(sys.argv[1]) if len(sys.argv) > 1 else 3
replication = int(sys.argv[2]) if len(sys.argv) > 2 else 2

out = f"""\
# Generated by scripts/gen_compose.py  ({n} DataNodes, replication factor {replication})
x-app: &app                        # every service uses the same image, built from this directory
  build: .
  image: mini-hdfs:latest

x-common-env: &common-env
  NAMENODE_HOST: namenode
  NAMENODE_PORT: "5000"
  # CLUSTER_TOKEN: change-me     # uncomment (on EVERY service) to require a shared secret

services:
  namenode:
    <<: *app
    command: ["python", "namenode.py"]
    environment:
      <<: *common-env
      NAMENODE_DATA_DIR: /data
      REPLICATION_FACTOR: "{replication}"
    volumes:
      - namenode-data:/data
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; socket.create_connection(('127.0.0.1', 5000), 2)"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  client:
    <<: *app
    command: ["python", "client.py"]
    environment:
      <<: *common-env
      CLIENT_PORT: "8000"
    ports:
      - "8000:8000"          # the only port published to the host
    depends_on:
      namenode:
        condition: service_healthy
    restart: unless-stopped
"""
for i in range(n):
    out += f"""
  datanode{i}:
    <<: *app
    command: ["python", "datanode.py"]
    environment:
      <<: *common-env
      DATANODE_ID: datanode{i}
      DATANODE_PORT: "6000"
      DATA_DIR: /data
    volumes:
      - datanode{i}-data:/data
    depends_on:
      namenode:
        condition: service_healthy
    restart: unless-stopped
"""
out += "\nvolumes:\n  namenode-data:\n" + "".join(f"  datanode{i}-data:\n" for i in range(n))
sys.stdout.write(out)
